[theme]
base = "dark"
primaryColor = "#CBA6F7"
backgroundColor = "#121212"
secondaryBackgroundColor = "#2C2C3A"
textColor = "#F1F1F1"
font = "sans serif"
[server]
headless = true
enableCORS = false
enableXsrfProtection = false